### ISSUE TITLE
Vaccination slots API inconsistency

### ISSUE THREAD

**Issue by dvalim** [PW-MiNI-IO2-2022-Group-1/grupa-o-aabs-backend#29]
Wedle specyfikacji sloty powinny być dostępne pod `/vaccination-slots`, a nie `/patient/vaccination-slots`, `/doctor/vaccination-slots`, etc.
Dodatkowo nie powinny być zpaginowane.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/51292024/171591091-1dbd529e-d01d-4b1c-b3c2-6d167a869906.png">

<img width="464" alt="image" src="https://user-images.githubusercontent.com/51292024/171591136-6839e261-bea8-41ca-ab1a-e1a58d335ab7.png">

**Comment by V1OL3TF0X** [comment]
@dvalim 
https://battnik90.stoplight.io/docs/io/5d8e12a96d7d6-get-vaccination-slots-schedule
Wg tego istnieje endpoint `/doctor/vaccination-slots` , który na dodatek ma paginację

**Comment by lavar3l** [comment]
To są dwa różne endpointy.

Endpoint, o którym mówi Dawid jest w namespace "Common" i zwraca listę dostępnych slotów możliwych do rejestracji. Takie sloty są potrzebne pacjentowi do zarejestrowania się na wizytę, zaś lekarzowi i adminowi do zmiany terminu wizyty. **Ten endpoint zastapił /patient/vaccination-slots, tak aby lekarz i admin również mieli dostęp do listy wolnych terminów.**

Endpoint /doctor/vaccination-slots służy natomiast to wyświetlenia grafiku lekarza (wszystkie stworzone przez niego sloty, łącznie z podpiętymi wizytami na zajęte terminy).

**Comment by V1OL3TF0X** [comment]
Jasne
