### ISSUE TITLE
[Patient] Certificate download

### ISSUE THREAD

**Issue by dvalim** [PW-MiNI-IO2-2022-Group-1/grupa-o-aabs-backend#31]
<img width="470" alt="image" src="https://user-images.githubusercontent.com/51292024/171591379-faf687c1-cb22-48d2-9530-c1e7eb7a8cfe.png">

**Comment by V1OL3TF0X** [comment]
#39

**Comment by V1OL3TF0X** [comment]
#39 solves this

**Comment by V1OL3TF0X** [comment]
solved by #39
